### ISSUE TITLE
Are outputs hooked up?

### ISSUE THREAD

**Issue by gksudolol** [dqrk0jeste/owl#1]
Hi! Really liking owl so far

But. When setting `output HDMI-A-1 0 0 1920 1080 60` it launches at 3840x2160 resolution (with or without output defined)

Testing with wlr-randr outputs `compositor doesn't support wlr-output-management-unstable-v1`

**Comment by dqrk0jeste** [comment]
hi! thank you for trying it out!

there is a problem when confiuring outputs, but i think i have found the issue. see, outputs have their modes, which is a discrete set, and setting the mode to anything other then those will cause the output to not commit its state. for example, my laptop monitor specifies 60.020Hz as its refresh rate, setting it to 60Hz fails. 
i need to implement some 'interpolation' for config values, that is, if you specify 60Hz, i want to find the mode that is closest to it. it is quite a bit of work, and a bit harder to test because i dont have many monitors, but will do. 

until that is implemented, could you please build owl from the latest commit, which introduces --debug option, run it with that and then paste the contents of /tmp/owl-logs and also your config, just to confirm if thats whats going on. thank you!

ps: i do plan on supporting wlr-output-management-unstable-v1 protocol, just after this is fixed.

**Comment by gksudolol** [comment]
Understandable, FWIW on hyprland it also defaults to 3840x2160 unless I set it manually to 1920x1080

In the end I leave it as default and just scale the output by 2 which brings it down to 1920x1080

Here's the owl log and configuration

[owl-logs.txt](https://github.com/user-attachments/files/17702434/owl-logs.txt)

```
env XDG_CURRENT_DESKTOP owl
env XDG_SESSION_DESKTOP owl
env XDG_SESSION_TYPE wayland
env QT_QPA_PLATFORM wayland
env QT_WAYLAND_DISABLE_WINDOWDECORATION 1
env QT_AUTO_SCREEN_SCALE_FACTOR 1

env XCURSOR_SIZE 24
env XCURSOR_THEME rose-pine

min_toplevel_size 10

keyboard_rate 30
keyboard_delay 200

natural_scroll 1
tap_to_click 1

output HDMI-A-1 0 0 1920 1080 60

workspace 1 HDMI-A-1
workspace 2 HDMI-A-1
workspace 3 HDMI-A-1
workspace 4 HDMI-A-1
workspace 5 HDMI-A-1
workspace 6 HDMI-A-1

master_count 1
master_ratio 0.5

border_width 3
outer_gaps 12
inner_gaps 6

cursor_theme rose-pine
cursor_size 24

inactive_border_color 72 82 99 256
active_border_color 194 150 235 256

keybind super+shift q exit

keybind super 1 workspace 1
keybind super 2 workspace 2
keybind super 3 workspace 3
keybind super 4 workspace 4
keybind super 5 workspace 5
keybind super 6 workspace 6

keybind super+shift 1 move_to_workspace 1
keybind super+shift 2 move_to_workspace 2
keybind super+shift 3 move_to_workspace 3
keybind super+shift 4 move_to_workspace 4
keybind super+shift 5 move_to_workspace 5
keybind super+shift 6 move_to_workspace 6

keybind super t run foot
keybind super x resize
keybind super z move
keybind super c kill_active
keybind super f switch_floating_state
```

**Comment by dqrk0jeste** [comment]
does not seem like there should be an issue here, as 1920x1080@60Hz is specified as a valid mode. maybe the issue is [here](https://github.com/dqrk0jeste/owl/blob/main/src/owl.c#L1376) because the mode is passed a a pointer that than goes out of scope when wlr_output_commit_state() is called, that would explain the 'invalid argument' error that pops in the logs. will investigate this a bit later.

**Comment by dqrk0jeste** [comment]
latest commit should have fixed the issue, can you check it out?

**Comment by gksudolol** [comment]
I think that's fixed it, other resolutions work also (just thought I'd test them all). Thanks!
